services:
  app:
    image: todo-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:3000
    ports:
      - 3001:80
    container_name: todo-frontend-prod
    environment:
      - NODE_ENV=production
