services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-the_database}
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data_prod:/data/db
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data_prod:/data
    restart: unless-stopped

  server:
    image: todo-backend-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: todo-backend-server
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - MONGO_URL=${MONGO_URL:-mongodb://the_username:the_password@mongo:27017/the_database}
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

volumes:
  mongo_data_prod:
  redis_data_prod:
