services:
  mongo:
    image: mongo:6.0-jammy
    ports:
      - 3457:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: phonebook
    volumes:
      - mongo_data:/data/db

  server:
    image: puhelinluettelo-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
    container_name: puhelinluettelo-backend-dev
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/phonebook?authSource=admin
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo_data:
